version: 0.0
os: linux
files:
  - source: output
    destination: /wwwroot/exchange-rate/
    overwrite: true
hooks:
  BeforeInstall:
    - location: stop_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_service.sh
      timeout: 300
      runas: root
