version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0 # Adjust based on your .NET Core version
    commands:
      - echo Installing dependencies...
      - yum update -y
      - yum install -y unzip

  pre_build:
    commands:
      - echo Restoring .NET Core dependencies...
      - dotnet restore

  build:
    commands:
      - echo Building the application...
      - dotnet clean 
      - dotnet publish -c Release -o output

  post_build:
    commands:
      - echo "=== Listing all files in workspace ==="
      - ls -R
      - echo Build phase completed.

artifacts:
  files:
    - output/**/*
    - appspec.yml
    - scripts/**/*
    - stop_service.sh
    - start_service.sh
