version: 0.0
os: linux
files:
  - source: output
    destination: /wwwroot/exchange-rate/
hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root
