version: 0.0
os: linux
files:
  - source: /
    destination: /wwwroot/exchange-rate/
hooks:
  BeforeInstall:
    - location: output/stop_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: output/start_service.sh
      timeout: 300
      runas: root
