version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 7.0 # Adjust based on your .NET Core version
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y unzip

  pre_build:
    commands:
      - echo Restoring .NET Core dependencies...
      - dotnet restore

  build:
    commands:
      - echo Building the application...
      - dotnet publish -c Release -o output

  post_build:
    commands:
      - echo Preparing for deployment...
      - zip -r deployment.zip output/
      - echo Build phase completed.

artifacts:
  files:
    - deployment.zip
